name: cdar
version: 0.1.0.0
synopsis: Exact real arithmetic using Centred Dyadic Approximations.
#-- description:         
license: BSD3
license-file: LICENSE
author: Jens Blanck
maintainer: jens.blanck@gmail.com
#-- copyright:           
category: Data
build-type: Simple
extra-source-files: README.md
#-- cabal-version:       >=1.10

ghc-options: -Wall -fno-warn-type-defaults -O2

dependencies:
  - base
  - containers
  - deepseq
  - integer-gmp

library:
  source-dirs: src/
  exposed-modules:
    - Data.CDAR
    - Data.CDAR.Classes
    - Data.CDAR.Extended
    - Data.CDAR.Approx
    - Data.CDAR.Dyadic
    - Data.CDAR.IntegerLog

tests:
  test:
    main: Test.hs
    source-dirs: test/
    dependencies:
      - QuickCheck
      - smallcheck
      - tasty-hunit
      - tasty-quickcheck
      - tasty-smallcheck
      - tasty
      - cdar
#  default-language: Haskell2010

# -- Benchmark bench-transcend
# --   type:                 exitcode-stdio-1.0
# --   main-is:              bench-transcend.hs
# --   build-depends:
# --       base >=4.7 && <4.9
# --     , containers >=0.5 && <0.6
# --     , deepseq >=1.3 && <1.5
# --     , integer-gmp >=0.5 && <1.1
# --     , cdar >= 0.1
# --     , criterion >= 1.1 && <1.2
# --     , parallel >=3.2 && <3.3
# --   hs-source-dirs:       bench
# --   default-language: Haskell2010

benchmarks:
  bench:
    main: bench.hs
    dependencies:
      - cdar
      - criterion
      - parallel
    source-dirs:       bench/
    ghc-options: -O2 -rtsopts

# -- Benchmark BinSplitPar
# --   type:                 exitcode-stdio-1.0
# --   main-is:              BinSplitPar.hs
# --   build-depends:
# --       base >=4.7 && <4.10
# --     , containers >=0.5 && <0.6
# --     , deepseq >=1.3 && <1.5
# --     , integer-gmp >=0.5 && <1.1
# --     , cdar >= 0.1
# --     , criterion >= 1.1 && <1.2
# --     , parallel >=3.2 && <3.3
# --     , monad-par 
# --   hs-source-dirs:       bench
# --   default-language: Haskell2010
# --   ghc-options:         -threaded -O2 -rtsopts

executables:
  logistic:
    source-dirs: examples/
    main: Logistic.hs
    dependencies: cdar
  examples:
    source-dirs: examples/
    main: Main.hs
    other-modules: ExamplesRump
    dependencies: cdar
    
